<?xml version="1.0" encoding="utf-8"?><Database Name="sellphone" Class="MyDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=den1.mssql7.gear.host;Initial Catalog=sellphone;Persist Security Info=True;User ID=sellphone" SettingsObjectName="PhoneShare.Properties.Settings" SettingsPropertyName="sellphoneConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Phone" Member="Phones">
    <Type Name="Phone">
      <Column Name="Code" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Color" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>